
Epoch 0:   5%|██████                                                                                                                         | 75/1564 [00:00<00:19, 76.80it/s, loss=2.18, v_num=p3nt]
/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:445: LightningDeprecationWarning: Setting `Trainer(gpus=0)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=0)` instead.
  rank_zero_deprecation(
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py:616: UserWarning: Checkpoint directory /home/notebooks/checkpoints/{epoch:d} exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
  | Name  | Type       | Params
-------------------------------------
0 | model | Sequential | 99.7 K
-------------------------------------
99.7 K    Trainable params
0         Non-trainable params
99.7 K    Total params
0.399     Total estimated model params size (MB)
/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:219: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:219: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.








Epoch 0:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 1371/1564 [00:17<00:02, 79.87it/s, loss=1.5, v_num=p3nt]









Epoch 1:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 1496/1564 [00:18<00:00, 81.75it/s, loss=1.2, v_num=p3nt]
Validation DataLoader 0:  50%|██████████████████████████████████████████████████████████████████▌                                                                   | 78/157 [00:00<00:00, 154.55it/s]








Epoch 2:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 1422/1564 [00:17<00:01, 80.10it/s, loss=1.08, v_num=p3nt]
Validation DataLoader 0:  12%|████████████████▏                                                                                                                     | 19/157 [00:00<00:00, 185.01it/s]










Epoch 4:   0%|                                                                                                                                | 1/1564 [00:00<00:17, 91.89it/s, loss=1.03, v_num=p3nt]








Epoch 4:  81%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                       | 1264/1564 [00:16<00:03, 78.65it/s, loss=0.957, v_num=p3nt]
/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py:657: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")
/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py:1385: UserWarning: `.test(ckpt_path=None)` was called without a model. The best model of the previous `fit` call will be used. You can pass `.test(ckpt_path='best')` to use the best model or `.test(ckpt_path='last')` to use the last model. If you pass a value, this warning will be silenced.
  rank_zero_warn(
Restoring states from the checkpoint path at /home/notebooks/checkpoints/{epoch:d}/epoch=3-step=5628.ckpt
Loaded model weights from checkpoint at /home/notebooks/checkpoints/{epoch:d}/epoch=3-step=5628.ckpt
/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:219: PossibleUserWarning: The dataloader, test_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.

Testing DataLoader 0: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 313/313 [00:01<00:00, 162.66it/s]
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃[1m        Test metric        [22m┃[1m       DataLoader 0        [22m┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│[36m         test_acc          [39m│[35m    0.5916000008583069     [39m│
│[36m         test_loss         [39m│[35m     1.116983413696289     [39m│
